2019-06-26 12:53:23,301 ERROR: Exception on /explore [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 37, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 21, in block "content"
    {%  include "_post.html" %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2019-06-26 12:53:50,077 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-06-26 12:53:56,796 ERROR: Exception on /explore [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 37, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %} {% endblock %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 21, in block "content"
    {%  include "_post.html" %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
2019-06-26 12:55:34,631 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-05 09:58:30,260 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:00:44,822 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:00:47,379 ERROR: Exception on /index [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', form=form, posts=posts.item)
AttributeError: 'Pagination' object has no attribute 'item'
2019-07-10 15:01:00,711 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:01:17,569 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:17:04,108 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:38:40,778 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
